feat(JOML): migrate majority of GrowingFlora module
Terasology/GrowingFlora pull request #26
Opened 2021-01-10 19:20 UTC by jdrueckert

2021-01-10 19:20 UTC, jdrueckert commented on src/main/java/org/terasology/gf/tree/TreeDestructionSystem.java
> +                Vector3i position = component.getPosition(new org.joml.Vector3i());
```suggestion
                Vector3i position = component.getPosition(new Vector3i());
```

2021-01-11 20:39 UTC, skaldarnar requested changes

2021-01-11 20:39 UTC, skaldarnar commented on src/main/java/org/terasology/gf/tree/lsystem/AdvancedLSystemTreeDefinition.java
> +        Matrix4f rotation = new Matrix4f().translationRotateScale(new Vector3f(),new Quaternionf().setAngleAxis(treeRotation,0,1,0), 1.0f);
I think @pollend told me to just use a quaternion for bascially the same code in `RecursiveTreeGeneratorLSystem`... see https://github.com/Terasology/CoreWorlds/commit/6484ebc671bf27511a7eebceeb67e19968d7f33c

2021-01-11 20:44 UTC, skaldarnar commented on src/main/java/org/terasology/gf/tree/lsystem/AdvancedLSystemTreeDefinition.java
> +        Matrix4f rotation = new Matrix4f().translationRotateScale(new Vector3f(),new Quaternionf().setAngleAxis(treeRotation,0,1,0), 1.0f);
However, it's not as straight forward, and this code isn't working properly anyways right now. Will add a TODO comment to pick this up later.

2021-01-11 20:47 UTC, skaldarnar approved these changes

2021-01-11 23:16 UTC, merged